<?php

use Illuminate\Database\Seeder;
use App\Paises;
class PaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
                    
            Paises::create([
                'iso'=>'AF',
                'nombre'=>'Afganistan',
                ]);

            Paises::create([
                'iso'=>'AX',
                'nombre'=>'Islas Gland',
                ]);
            Paises::create([
                'iso'=>'AL',
                'nombre'=>'Albania',
                ]);
            Paises::create([
                'iso'=>'DE',
                'nombre'=>'Alemania',
                ]);
            Paises::create([
                'iso'=>'AD',
                'nombre'=>'Andorra',
                ]);
            Paises::create([
                'iso'=>'AO',
                'nombre'=>'Angola',
                ]);
            Paises::create([
                'iso'=>'AI',
                'nombre'=>'Anguilla',
                ]);
            Paises::create([
                'iso'=>'AQ',
                'nombre'=>'Antartida',
                ]);
            Paises::create([
                'iso'=>'AG',
                'nombre'=>'Antigua y Barbuda',
                ]);
            Paises::create([
                'iso'=>'AN',
                'nombre'=>'Antillas Holandesas',
                ]);
            Paises::create([
                'iso'=>'SA',
                'nombre'=>'Arabia Saudi',
                ]);
            Paises::create([
                'iso'=>'DZ',
                'nombre'=>'Argelia',
                ]);
            Paises::create([
                'iso'=>'AR',
                'nombre'=>'Argentina',
                ]);
            Paises::create([
                'iso'=>'AM',
                'nombre'=>'Armenia',
                ]);
            Paises::create([
                'iso'=>'AW',
                'nombre'=>'Aruba',
                ]);
            Paises::create([
                'iso'=>'AU',
                'nombre'=>'Australia',
                ]);
            Paises::create([
                'iso'=>'AT',
                'nombre'=>'Austria',
                ]);
            Paises::create([
                'iso'=>'AZ',
                'nombre'=>'Azerbaiyan',
                ]);
            Paises::create([
                'iso'=>'BS',
                'nombre'=>'Bahamas',
                ]);
            Paises::create([
                'iso'=>'BH',
                'nombre'=>'Bahrein',
                ]);
            Paises::create([
                'iso'=>'BD',
                'nombre'=>'Bangladesh',
                ]);
            Paises::create([
                'iso'=>'BB',
                'nombre'=>'Barbados',
                ]);
            Paises::create([
                'iso'=>'BY',
                'nombre'=>'Bielorrusia',
                ]);
            Paises::create([
                'iso'=>'BE',
                'nombre'=>'Belgica',
                ]);
            Paises::create([
                'iso'=>'BZ',
                'nombre'=>'Belice',
                ]);
            Paises::create([
                'iso'=>'BJ',
                'nombre'=>'Benin',
                ]);
            Paises::create([
                'iso'=>'BM',
                'nombre'=>'Bermudas',
                ]);
            Paises::create([
                'iso'=>'BT',
                'nombre'=>'Bhutan',
                ]);
            Paises::create([
                'iso'=>'BO',
                'nombre'=>'Bolivia',
                ]);
            Paises::create([
                'iso'=>'BA',
                'nombre'=>'Bosnia y Herzegovina',
                ]);
            Paises::create([
                'iso'=>'BW',
                'nombre'=>'Botsuana',
                ]);
            Paises::create([
                'iso'=>'BV',
                'nombre'=>'Isla Bouvet',
                ]);
            Paises::create([
                'iso'=>'BR',
                'nombre'=>'Brasil',
                ]);
            Paises::create([
                'iso'=>'BN',
                'nombre'=>'Brunei',
                ]);
            Paises::create([
                'iso'=>'BG',
                'nombre'=>'Bulgaria',
                ]);
            Paises::create([
                'iso'=>'BF',
                'nombre'=>'Burkina Faso',
                ]);
            Paises::create([
                'iso'=>'BI',
                'nombre'=>'Burundi',
                ]);
            Paises::create([
                'iso'=>'CV',
                'nombre'=>'Cabo Verde',
                ]);
            Paises::create([
                'iso'=>'KY',
                'nombre'=>'Islas Caiman',
                ]);
            Paises::create([
                'iso'=>'KH',
                'nombre'=>'Camboya',
                ]);
            Paises::create([
                'iso'=>'CM',
                'nombre'=>'Camerun',
                ]);
            Paises::create([
                'iso'=>'CA',
                'nombre'=>'Canada',
                ]);
            Paises::create([
                'iso'=>'CF',
                'nombre'=>'Republica Centroafricana',
                ]);
            Paises::create([
                'iso'=>'TD',
                'nombre'=>'Chad',
                ]);
            Paises::create([
                'iso'=>'CZ',
                'nombre'=>'Republica Checa',
                ]);
            Paises::create([
                'iso'=>'CL',
                'nombre'=>'Chile',
                ]);
            Paises::create([
                'iso'=>'CN',
                'nombre'=>'China',
                ]);
            Paises::create([
                'iso'=>'CY',
                'nombre'=>'Chipre',
                ]);
            Paises::create([
                'iso'=>'CX',
                'nombre'=>'Isla de Navidad',
                ]);
            Paises::create([
                'iso'=>'VA',
                'nombre'=>'Ciudad del Vaticano',
                ]);
            Paises::create([
                'iso'=>'CC',
                'nombre'=>'Islas Cocos',
                ]);
            Paises::create([
                'iso'=>'CO',
                'nombre'=>'Colombia',
                ]);
            Paises::create([
                'iso'=>'KM',
                'nombre'=>'Comoras',
                ]);
            Paises::create([
                'iso'=>'CD',
                'nombre'=>'Republica Democratica del Congo',
                ]);
            Paises::create([
                'iso'=>'CG',
                'nombre'=>'Congo',
                ]);
            Paises::create([
                'iso'=>'CK',
                'nombre'=>'Islas Cook',
                ]);
            Paises::create([
                'iso'=>'KP',
                'nombre'=>'Corea del Norte',
                ]);
            Paises::create([
                'iso'=>'KR',
                'nombre'=>'Corea del Sur',
                ]);
            Paises::create([
                'iso'=>'CI',
                'nombre'=>'Costa de Marfil',
                ]);
            Paises::create([
                'iso'=>'CR',
                'nombre'=>'Costa Rica',
                ]);
            Paises::create([
                'iso'=>'HR',
                'nombre'=>'Croacia',
                ]);
            Paises::create([
                'iso'=>'CU',
                'nombre'=>'Cuba',
                ]);
            Paises::create([
                'iso'=>'DK',
                'nombre'=>'Dinamarca',
                ]);
            Paises::create([
                'iso'=>'DM',
                'nombre'=>'Dominica',
                ]);
            Paises::create([
                'iso'=>'DO',
                'nombre'=>'Republica Dominicana',
                ]);
            Paises::create([
                'iso'=>'EC',
                'nombre'=>'Ecuador',
                ]);
            Paises::create([
                'iso'=>'EG',
                'nombre'=>'Egipto',
                ]);
            Paises::create([
                'iso'=>'SV',
                'nombre'=>'El Salvador',
                ]);
            Paises::create([
                'iso'=>'AE',
                'nombre'=>'Emiratos arabes Unidos',
                ]);
            Paises::create([
                'iso'=>'ER',
                'nombre'=>'Eritrea',
                ]);
            Paises::create([
                'iso'=>'SK',
                'nombre'=>'Eslovaquia',
                ]);
            Paises::create([
                'iso'=>'SI',
                'nombre'=>'Eslovenia',
                ]);
            Paises::create([
                'iso'=>'ES',
                'nombre'=>'Espana',
                ]);
            Paises::create([
                'iso'=>'UM',
                'nombre'=>'Islas ultramarinas de Estados Unidos',
                ]);
            Paises::create([
                'iso'=>'US',
                'nombre'=>'Estados Unidos',
                ]);
            Paises::create([
                'iso'=>'EE',
                'nombre'=>'Estonia',
                ]);
            Paises::create([
                'iso'=>'ET',
                'nombre'=>'Etiopia',
                ]);
            Paises::create([
                'iso'=>'FO',
                'nombre'=>'Islas Feroe',
                ]);
            Paises::create([
                'iso'=>'PH',
                'nombre'=>'Filipinas',
                ]);
            Paises::create([
                'iso'=>'FI',
                'nombre'=>'Finlandia',
                ]);
            Paises::create([
                'iso'=>'FJ',
                'nombre'=>'Fiyi',
                ]);
            Paises::create([
                'iso'=>'FR',
                'nombre'=>'Francia',
                ]);
            Paises::create([
                'iso'=>'GA',
                'nombre'=>'Gabon',
                ]);
            Paises::create([
                'iso'=>'GM',
                'nombre'=>'Gambia',
                ]);
            Paises::create([
                'iso'=>'GE',
                'nombre'=>'Georgia',
                ]);
            Paises::create([
                'iso'=>'GS',
                'nombre'=>'Islas Georgias del Sur y Sandwich del Sur',
                ]);
            Paises::create([
                'iso'=>'GH',
                'nombre'=>'Ghana',
                ]);
            Paises::create([
                'iso'=>'GI',
                'nombre'=>'Gibraltar',
                ]);
            Paises::create([
                'iso'=>'GD',
                'nombre'=>'Granada',
                ]);
            Paises::create([
                'iso'=>'GR',
                'nombre'=>'Grecia',
                ]);
            Paises::create([
                'iso'=>'GL',
                'nombre'=>'Groenlandia',
                ]);
            Paises::create([
                'iso'=>'GP',
                'nombre'=>'Guadalupe',
                ]);
            Paises::create([
                'iso'=>'GU',
                'nombre'=>'Guam',
                ]);
            Paises::create([
                'iso'=>'GT',
                'nombre'=>'Guatemala',
                ]);
            Paises::create([
                'iso'=>'GF',
                'nombre'=>'Guayana Francesa',
                ]);
            Paises::create([
                'iso'=>'GN',
                'nombre'=>'Guinea',
                ]);
            Paises::create([
                'iso'=>'GQ',
                'nombre'=>'Guinea Ecuatorial',
                ]);
            Paises::create([
                'iso'=>'GW',
                'nombre'=>'Guinea-Bissau',
                ]);
            Paises::create([
                'iso'=>'GY',
                'nombre'=>'Guyana',
                ]);
            Paises::create([
                'iso'=>'HT',
                'nombre'=>'Haiti',
                ]);
            Paises::create([
                'iso'=>'HM',
                'nombre'=>'Islas Heard y McDonald',
                ]);
            Paises::create([
                'iso'=>'HN',
                'nombre'=>'Honduras',
                ]);
            Paises::create([
                'iso'=>'HK',
                'nombre'=>'Hong Kong',
                ]);
            Paises::create([
                'iso'=>'HU',
                'nombre'=>'Hungria',
                ]);
            Paises::create([
                'iso'=>'IN',
                'nombre'=>'India',
                ]);
            Paises::create([
                'iso'=>'ID',
                'nombre'=>'Indonesia',
                ]);
            Paises::create([
                'iso'=>'IR',
                'nombre'=>'Iran',
                ]);
            Paises::create([
                'iso'=>'IQ',
                'nombre'=>'Iraq',
                ]);
            Paises::create([
                'iso'=>'IE',
                'nombre'=>'Irlanda',
                ]);
            Paises::create([
                'iso'=>'IS',
                'nombre'=>'Islandia',
                ]);
            Paises::create([
                'iso'=>'IL',
                'nombre'=>'Israel',
                ]);
            Paises::create([
                'iso'=>'IT',
                'nombre'=>'Italia',
                ]);
            Paises::create([
                'iso'=>'JM',
                'nombre'=>'Jamaica',
                ]);
            Paises::create([
                'iso'=>'JP',
                'nombre'=>'Japon',
                ]);
            Paises::create([
                'iso'=>'JO',
                'nombre'=>'Jordania',
                ]);
            Paises::create([
                'iso'=>'KZ',
                'nombre'=>'Kazajstan',
                ]);
            Paises::create([
                'iso'=>'KE',
                'nombre'=>'Kenia',
                ]);
            Paises::create([
                'iso'=>'KG',
                'nombre'=>'Kirguistan',
                ]);
            Paises::create([
                'iso'=>'KI',
                'nombre'=>'Kiribati',
                ]);
            Paises::create([
                'iso'=>'KW',
                'nombre'=>'Kuwait',
                ]);
            Paises::create([
                'iso'=>'LA',
                'nombre'=>'Laos',
                ]);
            Paises::create([
                'iso'=>'LS',
                'nombre'=>'Lesotho',
                ]);
            Paises::create([
                'iso'=>'LV',
                'nombre'=>'Letonia',
                ]);
            Paises::create([
                'iso'=>'LB',
                'nombre'=>'Libano',
                ]);
            Paises::create([
                'iso'=>'LR',
                'nombre'=>'Liberia',
                ]);
            Paises::create([
                'iso'=>'LY',
                'nombre'=>'Libia',
                ]);
            Paises::create([
                'iso'=>'LI',
                'nombre'=>'Liechtenstein',
                ]);
            Paises::create([
                'iso'=>'LT',
                'nombre'=>'Lituania',
                ]);
            Paises::create([
                'iso'=>'LU',
                'nombre'=>'Luxemburgo',
                ]);
            Paises::create([
                'iso'=>'MO',
                'nombre'=>'Macao',
                ]);
            Paises::create([
                'iso'=>'MK',
                'nombre'=>'ARY Macedonia',
                ]);
            Paises::create([
                'iso'=>'MG',
                'nombre'=>'Madagascar',
                ]);
            Paises::create([
                'iso'=>'MY',
                'nombre'=>'Malasia',
                ]);
            Paises::create([
                'iso'=>'MW',
                'nombre'=>'Malawi',
                ]);
            Paises::create([
                'iso'=>'MV',
                'nombre'=>'Maldivas',
                ]);
            Paises::create([
                'iso'=>'ML',
                'nombre'=>'Mali',
                ]);
            Paises::create([
                'iso'=>'MT',
                'nombre'=>'Malta',
                ]);
            Paises::create([
                'iso'=>'FK',
                'nombre'=>'Islas Malvinas',
                ]);
            Paises::create([
                'iso'=>'MP',
                'nombre'=>'Islas Marianas del Norte',
                ]);
            Paises::create([
                'iso'=>'MA',
                'nombre'=>'Marruecos',
                ]);
            Paises::create([
                'iso'=>'MH',
                'nombre'=>'Islas Marshall',
                ]);
            Paises::create([
                'iso'=>'MQ',
                'nombre'=>'Martinica',
                ]);
            Paises::create([
                'iso'=>'MU',
                'nombre'=>'Mauricio',
                ]);
            Paises::create([
                'iso'=>'MR',
                'nombre'=>'Mauritania',
                ]);
            Paises::create([
                'iso'=>'YT',
                'nombre'=>'Mayotte',
                ]);
            Paises::create([
                'iso'=>'MX',
                'nombre'=>'Mexico',
                ]);
            Paises::create([
                'iso'=>'FM',
                'nombre'=>'Micronesia',
                ]);
            Paises::create([
                'iso'=>'MD',
                'nombre'=>'Moldavia',
                ]);
            Paises::create([
                'iso'=>'MC',
                'nombre'=>'Monaco',
                ]);
            Paises::create([
                'iso'=>'MN',
                'nombre'=>'Mongolia',
                ]);
            Paises::create([
                'iso'=>'MS',
                'nombre'=>'Montserrat',
                ]);
            Paises::create([
                'iso'=>'MZ',
                'nombre'=>'Mozambique',
                ]);
            Paises::create([
                'iso'=>'MM',
                'nombre'=>'Myanmar',
                ]);
            Paises::create([
                'iso'=>'NA',
                'nombre'=>'Namibia',
                ]);
            Paises::create([
                'iso'=>'NR',
                'nombre'=>'Nauru',
                ]);
            Paises::create([
                'iso'=>'NP',
                'nombre'=>'Nepal',
                ]);
            Paises::create([
                'iso'=>'NI',
                'nombre'=>'Nicaragua',
                ]);
            Paises::create([
                'iso'=>'NE',
                'nombre'=>'Niger',
                ]);
            Paises::create([
                'iso'=>'NG',
                'nombre'=>'Nigeria',
                ]);
            Paises::create([
                'iso'=>'NU',
                'nombre'=>'Niue',
                ]);
            Paises::create([
                'iso'=>'NF',
                'nombre'=>'Isla Norfolk',
                ]);
            Paises::create([
                'iso'=>'NO',
                'nombre'=>'Noruega',
                ]);
            Paises::create([
                'iso'=>'NC',
                'nombre'=>'Nueva Caledonia',
                ]);
            Paises::create([
                'iso'=>'NZ',
                'nombre'=>'Nueva Zelanda',
                ]);
            Paises::create([
                'iso'=>'OM',
                'nombre'=>'Oman',
                ]);
            Paises::create([
                'iso'=>'NL',
                'nombre'=>'Paises Bajos',
                ]);
            Paises::create([
                'iso'=>'PK',
                'nombre'=>'Pakistan',
                ]);
            Paises::create([
                'iso'=>'PW',
                'nombre'=>'Palau',
                ]);
            Paises::create([
                'iso'=>'PS',
                'nombre'=>'Palestina',
                ]);
            Paises::create([
                'iso'=>'PA',
                'nombre'=>'Panama',
                ]);
            Paises::create([
                'iso'=>'PG',
                'nombre'=>'Papua Nueva Guinea',
                ]);
            Paises::create([
                'iso'=>'PY',
                'nombre'=>'Paraguay',
                ]);
            Paises::create([
                'iso'=>'PE',
                'nombre'=>'Peru',
                ]);
            Paises::create([
                'iso'=>'PN',
                'nombre'=>'Islas Pitcairn',
                ]);
            Paises::create([
                'iso'=>'PF',
                'nombre'=>'Polinesia Francesa',
                ]);
            Paises::create([
                'iso'=>'PL',
                'nombre'=>'Polonia',
                ]);
            Paises::create([
                'iso'=>'PT',
                'nombre'=>'Portugal',
                ]);
            Paises::create([
                'iso'=>'PR',
                'nombre'=>'Puerto Rico',
                ]);
            Paises::create([
                'iso'=>'QA',
                'nombre'=>'Qatar',
                ]);
            Paises::create([
                'iso'=>'GB',
                'nombre'=>'Reino Unido',
                ]);
            Paises::create([
                'iso'=>'RE',
                'nombre'=>'Reunion',
                ]);
            Paises::create([
                'iso'=>'RW',
                'nombre'=>'Ruanda',
                ]);
            Paises::create([
                'iso'=>'RO',
                'nombre'=>'Rumania',
                ]);
            Paises::create([
                'iso'=>'RU',
                'nombre'=>'Rusia',
                ]);
            Paises::create([
                'iso'=>'EH',
                'nombre'=>'Sahara Occidental',
                ]);
            Paises::create([
                'iso'=>'SB',
                'nombre'=>'Islas Salomon',
                ]);
            Paises::create([
                'iso'=>'WS',
                'nombre'=>'Samoa',
                ]);
            Paises::create([
                'iso'=>'AS',
                'nombre'=>'Samoa Americana',
                ]);
            Paises::create([
                'iso'=>'KN',
                'nombre'=>'San Cristobal y Nevis',
                ]);
            Paises::create([
                'iso'=>'SM',
                'nombre'=>'San Marino',
                ]);
            Paises::create([
                'iso'=>'PM',
                'nombre'=>'San Pedro y Miquelon',
                ]);
            Paises::create([
                'iso'=>'VC',
                'nombre'=>'San Vicente y las Granadinas',
                ]);
            Paises::create([
                'iso'=>'SH',
                'nombre'=>'Santa Helena',
                ]);
            Paises::create([
                'iso'=>'LC',
                'nombre'=>'Santa Lucia',
                ]);
            Paises::create([
                'iso'=>'ST',
                'nombre'=>'Santo Tome y Principe',
                ]);
            Paises::create([
                'iso'=>'SN',
                'nombre'=>'Senegal',
                ]);
            Paises::create([
                'iso'=>'CS',
                'nombre'=>'Serbia y Montenegro',
                ]);
            Paises::create([
                'iso'=>'SC',
                'nombre'=>'Seychelles',
                ]);
            Paises::create([
                'iso'=>'SL',
                'nombre'=>'Sierra Leona',
                ]);
            Paises::create([
                'iso'=>'SG',
                'nombre'=>'Singapur',
                ]);
            Paises::create([
                'iso'=>'SY',
                'nombre'=>'Siria',
                ]);
            Paises::create([
                'iso'=>'SO',
                'nombre'=>'Somalia',
                ]);
            Paises::create([
                'iso'=>'LK',
                'nombre'=>'Sri Lanka',
                ]);
            Paises::create([
                'iso'=>'SZ',
                'nombre'=>'Suazilandia',
                ]);
            Paises::create([
                'iso'=>'ZA',
                'nombre'=>'Sudafrica',
                ]);
            Paises::create([
                'iso'=>'SD',
                'nombre'=>'Sudan',
                ]);
            Paises::create([
                'iso'=>'SE',
                'nombre'=>'Suecia',
                ]);
            Paises::create([
                'iso'=>'CH',
                'nombre'=>'Suiza',
                ]);
            Paises::create([
                'iso'=>'SR',
                'nombre'=>'Surinam',
                ]);
            Paises::create([
                'iso'=>'SJ',
                'nombre'=>'Svalbard y Jan Mayen',
                ]);
            Paises::create([
                'iso'=>'TH',
                'nombre'=>'Tailandia',
                ]);
            Paises::create([
                'iso'=>'TW',
                'nombre'=>'Taiwan',
                ]);
            Paises::create([
                'iso'=>'TZ',
                'nombre'=>'Tanzania',
                ]);
            Paises::create([
                'iso'=>'TJ',
                'nombre'=>'Tayikistan',
                ]);
            Paises::create([
                'iso'=>'IO',
                'nombre'=>'Territorio Britanico del Oceano indico',
                ]);
            Paises::create([
                'iso'=>'TF',
                'nombre'=>'Territorios Australes Franceses',
                ]);
            Paises::create([
                'iso'=>'TL',
                'nombre'=>'Timor Oriental',
                ]);
            Paises::create([
                'iso'=>'TG',
                'nombre'=>'Togo',
                ]);
            Paises::create([
                'iso'=>'TK',
                'nombre'=>'Tokelau',
                ]);
            Paises::create([
                'iso'=>'TO',
                'nombre'=>'Tonga',
                ]);
            Paises::create([
                'iso'=>'TT',
                'nombre'=>'Trinidad y Tobago',
                ]);
            Paises::create([
                'iso'=>'TN',
                'nombre'=>'Tunez',
                ]);
            Paises::create([
                'iso'=>'TC',
                'nombre'=>'Islas Turcas y Caicos',
                ]);
            Paises::create([
                'iso'=>'TM',
                'nombre'=>'Turkmenistan',
                ]);
            Paises::create([
                'iso'=>'TR',
                'nombre'=>'Turquia',
                ]);
            Paises::create([
                'iso'=>'TV',
                'nombre'=>'Tuvalu',
                ]);
            Paises::create([
                'iso'=>'UA',
                'nombre'=>'Ucrania',
                ]);
            Paises::create([
                'iso'=>'UG',
                'nombre'=>'Uganda',
                ]);
            Paises::create([
                'iso'=>'UY',
                'nombre'=>'Uruguay',
                ]);
            Paises::create([
                'iso'=>'UZ',
                'nombre'=>'Uzbekistan',
                ]);
            Paises::create([
                'iso'=>'VU',
                'nombre'=>'Vanuatu',
                ]);
            Paises::create([
                'iso'=>'VE',
                'nombre'=>'Venezuela',
                ]);
            Paises::create([
                'iso'=>'VN',
                'nombre'=>'Vietnam',
                ]);
            Paises::create([
                'iso'=>'VG',
                'nombre'=>'Islas Virgenes Britanicas',
                ]);
            Paises::create([
                'iso'=>'VI',
                'nombre'=>'Islas Virgenes de los Estados Unidos',
                ]);
            Paises::create([
                'iso'=>'WF',
                'nombre'=>'Wallis y Futuna',
                ]);
            Paises::create([
                'iso'=>'YE',
                'nombre'=>'Yemen',
                ]);
            Paises::create([
                'iso'=>'DJ',
                'nombre'=>'Yibuti',
                ]);
            Paises::create([
                'iso'=>'ZM',
                'nombre'=>'Zambia',
                ]);
            Paises::create([
                'iso'=>'ZW',
                'nombre'=>'Zimbabue',
                ]);
    }
}
